### ISSUE TITLE
Caused by: java.lang.NullPointerException: appConfig.gameDBUrl must not be null

### ISSUE THREAD

**Issue by cikichen** [farewell12345/FAQ-Bot-QQ#6]
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at io.farewell12345.github.faqbot.MainKt.main(Main.kt:21)
	at io.farewell12345.github.faqbot.MainKt$$$main.invoke(Unknown Source)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:205)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
	at io.farewell12345.github.faqbot.MainKt.main(Main.kt)
Caused by: java.lang.NullPointerException: appConfig.gameDBUrl must not be null
	at io.farewell12345.github.faqbot.DTO.DB.DB.<clinit>(DB.kt:16)
	... 7 more
```

**Comment by cikichen** [comment]
还一个问题是README里面写的创建faq数据库，代码里面的jdbc却是fqa，报错搞了半天才发现问题

**Comment by Dev-Umb** [comment]
很抱歉，是我的问题

**Comment by Dev-Umb** [comment]
已对java/io/farewell12345/github/faqbot/AppConfig.java进行修改，以config中配置的数据库url为唯一url

**Comment by cikichen** [comment]
> 已对java/io/farewell12345/github/faqbot/AppConfig.java进行修改，以config中配置的数据库url为唯一url

SQL不全，缺少群组和游戏相关的表，还有gameAPI能添加README吗？

**Comment by Dev-Umb** [comment]
相关表已添加到SQL文件夹下，readme已更新
